#!/bin/bash 

// Run exp_test

var exec = require('child_process').exec
function puts(error, stdout, stderr) {
    console.log(stderr)
    console.log(stdout)
}
exec('cp ../PhaseI/Pass.g Pass.g; \
      cp ../PhaseI/output/PassLexer.java ../PhaseI/output/PassParser.java .; \
      cp ../PhaseI/output/Pass.tokens Pass.tokens; \
      java org.antlr.Tool Pass.g; \
      javac *.java; \
      java Test; \
      rm Pass.g PassLexer.java PassParser.java Pass.tokens *.class;', puts)\n