#!/bin/bash 

// Run snippet_tests
// each snippet test is found in a file named input#. Ex: input1

var exec = require('child_process').exec
function puts(error, stdout, stderr) {
    console.log(stderr)
    console.log(stdout)
}
exec('cp ../PhaseI/Pass.g Pass.g; \
      cp ../PhaseI/output/PassLexer.java ../PhaseI/output/PassParser.java .; \
      cp ../PhaseI/output/Pass.tokens Pass.tokens; \
      java org.antlr.Tool Pass.g; \
      javac *.java; \
      java TestSnippets input1; \
      java TestSnippets input2; \
      java TestSnippets input3; \
      rm Pass.g PassLexer.java PassParser.java Pass.tokens *.class;', puts)\n