JFLAGS = -g
JC = javac
.SUFFIXES: .java 
.java:
	javac $<

default:
	cp ../../PhaseI/Pass.g Pass.g;
	java org.antlr.Tool Pass.g; 
	javac TestSnippets.java;
   
tests: 
	@echo "Testing all Snippets in ./Snippets. Test passes if no error" ;
	@echo "-----------------------";
	java TestSnippets ./input1;
	java TestSnippets ./input2;
	java TestSnippets ./input3;
	java TestSnippets ./input4;
	java TestSnippets ./input5;
	java TestSnippets ./input6;
	java TestSnippets ./input7;
	java TestSnippets ./input8;
	java TestSnippets ./input9;
	java TestSnippets ./input10;
	java TestSnippets ./input11;
	java TestSnippets ./input12;
	java TestSnippets ./input13;
	java TestSnippets ./input14;
	java TestSnippets ./input15;
	java TestSnippets ./input16;
	java TestSnippets ./input17;
	java TestSnippets ./input18;
	java TestSnippets ./input19;
	java TestSnippets ./input20;
	java TestSnippets ./input21;
	java TestSnippets ./input22;
	java TestSnippets ./input23;
	java TestSnippets ./input24;
	java TestSnippets ./input25;
	java TestSnippets ./input26;
	java TestSnippets ./input27;
	java TestSnippets ./input28;
	java TestSnippets ./input29;
	java TestSnippets ./input30;
	java TestSnippets ./input31;
	java TestSnippets ./input32;
	java TestSnippets ./input33;
	java TestSnippets ./input34;
	java TestSnippets ./input35;
	java TestSnippets ./input36;
	java TestSnippets ./input37;
	java TestSnippets ./input38;
	java TestSnippets ./input39;
	java TestSnippets ./input40;
	java TestSnippets ./input41;
	java TestSnippets ./input42;
	java TestSnippets ./input43;
	java TestSnippets ./input44;
	java TestSnippets ./input45;
	java TestSnippets ./input46;
	java TestSnippets ./input47;
	java TestSnippets ./input48;
	java TestSnippets ./input49;
	java TestSnippets ./input50;
	java TestSnippets ./input51;
	java TestSnippets ./input52;
	java TestSnippets ./input53;
	java TestSnippets ./input54;
	java TestSnippets ./input55;
	java TestSnippets ./input56;
	java TestSnippets ./input57;
	java TestSnippets ./input58;
	java TestSnippets ./input59;
	java TestSnippets ./input60;
	java TestSnippets ./input61;
	java TestSnippets ./input62;
	java TestSnippets ./input63;
	java TestSnippets ./input64;
	java TestSnippets ./input65;
	java TestSnippets ./input66;
	java TestSnippets ./input67;
	java TestSnippets ./input68;
	java TestSnippets ./input69;
	java TestSnippets ./input70;
	java TestSnippets ./input71;
	java TestSnippets ./input72;
	java TestSnippets ./input73;
	java TestSnippets ./input74;
	java TestSnippets ./input75;
	java TestSnippets ./input76;



clean:
	$(RM) *.class PassLexer.java PassParser.java Pass.tokens Pass.g
